
#ifndef SRC_CONFIG_ECF_PHYSICS_PHYSICS_H_
#define SRC_CONFIG_ECF_PHYSICS_PHYSICS_H_

namespace espreso {

enum class PHYSICS {
	ADVECTION_DIFFUSION_2D,
	ADVECTION_DIFFUSION_3D,
	STRUCTURAL_MECHANICS_2D,
	STRUCTURAL_MECHANICS_3D,
	SHALLOW_WATER_2D
};

}


#endif /* SRC_CONFIG_ECF_PHYSICS_PHYSICS_H_ */
