
stages:
  - benchmarks
  - release

before_script:
  - export SPACK_ROOT=/opt/spack
  - . $SPACK_ROOT/share/spack/setup-env.sh
  - . env/paths.default
  - ml gcc openmpi intel-mkl cmake
  - cp install/build.config.gcc build.config

MKL32:
  stage: benchmarks
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=MKL --INT_WIDTH=32
    - ./waf install -j8
    - nosetests -v

MKL64:
  stage: benchmarks
  only:
    - triggers
  script:
    - ./waf configure --SOLVER=MKL --INT_WIDTH=64
    - ./waf install -j8
    - nosetests -v

GITHUB:
  stage: release
  only:
    - triggers
  script:
    - if ! git remote | grep release > /dev/null; then
        git remote add release git@github.com:It4innovations/espreso.git;
      fi
    - git checkout master
    - git pull origin master
    - git push release master
