
stages:
  - benchmarks
  - release

before_script:
  - export SPACK_ROOT=/opt/spack
  - . $SPACK_ROOT/share/spack/setup-env.sh
  - export PATH=./build/:$PATH
  - export LD_LIBRARY_PATH=./build/:$LD_LIBRARY_PATH 
  - ml gcc openmpi intel-mkl hypre parmetis

MKL32:
  stage: benchmarks
  only:
    - triggers
  script:
    - ./waf configure
    - ./waf -j8
    - nosetests -v

GITHUB:
  stage: release
  only:
    - triggers
  script:
    - if ! git remote | grep release > /dev/null; then
        git remote add release git@github.com:It4innovations/espreso.git;
      fi
    - git checkout master
    - git pull origin master
    - git push release master
