
import os
import glob

def configure(ctx):
    pass

def build(ctx):
    ctx.objects(
        source = ctx.path.ant_glob('**/*.cpp'),
        use    = "espreso_includes",
        target = "output"
    )
