
#ifndef SRC_PHYSICS_ASSEMBLER_KERNELS_STRUCTURALMECHANICS_KERNEL_H_
#define SRC_PHYSICS_ASSEMBLER_KERNELS_STRUCTURALMECHANICS_KERNEL_H_

#include "kernel.h"

namespace espreso {

struct StructuralMechanicsKernel: public Kernel
{

};

}



#endif /* SRC_PHYSICS_ASSEMBLER_KERNELS_STRUCTURALMECHANICS_KERNEL_H_ */
