
from waflib.Tools.ccroot import link_task

# Reconfigure build string to fit our requirements
class cxxprogram(link_task):
    vars    = ['LINKDEPS']
    ext_out = ['.bin']
    inst_to = '${BINDIR}',
    run_str = '${LINK_CXX} \
               ${LINKFLAGS} \
               ${CXXLNK_SRC_F}${SRC} \
               ${CXXLNK_TGT_F}${TGT[0].abspath()} \
               ${RPATH_ST:RPATH} \
               ${FRAMEWORKPATH_ST:FRAMEWORKPATH} \
               ${FRAMEWORK_ST:FRAMEWORK} \
               ${ARCH_ST:ARCH} \
\
               ${STLIB_MARKER} \
               -Wl,--start-group \
               ${STLIBPATH_ST:STLIBPATH} \
               ${STLIB_ST:STLIB} \
               -Wl,--end-group \
\
               ${SHLIB_MARKER} \
               ${LIBPATH_ST:LIBPATH} \
               ${LIB_ST:LIB} \
               ${LDFLAGS} \
\
               ${STLIB_MARKER} \
               -Wl,--start-group \
               ${STLIBPATH_ST:STLIBPATH} \
               ${STLIB_ST:POSTSTLIB} \
               -Wl,--end-group \
\
               ${SHLIB_MARKER}'

class cxxshlib(cxxprogram):
    pass

def configure(ctx):
    pass


def build(ctx):

    ctx.program(
        source       = "espreso.cpp",
        target       = "espreso",
        use          = "basis globals config wrappers input mesh output bem assembler feti multigrid",
        install_path = ctx.ROOT + "/bin"
    )

    ctx.program(
        source       = "ecfexport.cpp",
        target       = "ecfexport",
        use          = "basis globals config wrappers output mesh input",
        install_path = ctx.ROOT + "/bin"
    )

    return
    ctx.program(
        source       = "ecfchecker.cpp",
        target       = "ecfchecker",
        use          = "basis config wrappers",
        install_path = ctx.ROOT + "/bin"
    )

    ctx.program(
        source       = "apitest.cpp",
        target       = "apitest",
        use          = "feti4i",
        install_path = ctx.ROOT + "/bin"
    )

    ctx.env = ctx.all_envs["solver"];
    ctx.lib = (ctx.stlib, ctx.shlib)[ctx.env.LIBTYPE == "SHARED"]
    ctx.lib(
        source       = "apiwrapper/wrapper.cpp",
        target       = "feti4i",
        use          = "basis config wrappers input mesh feti multigrid assembler output bem",
        install_path = ctx.ROOT + "/lib"
    )


